default: &default
  adapter: mysql2
  host: localhost
  pool: 5
  encoding: utf8

# username and password should be read from environment variables,
# but this is just an experiment application. It is OK to be hacked.
development:
  <<: *default
  adapter: mysql2
  database: performance_dev
  username: performance
  password: performance

test:
  <<: *default
  database: performance_test
  username: performance
  password: performance

